### ISSUE TITLE
Kevin Office Hours 

### ISSUE THREAD

**Issue by d-alex-hughes** [mids-w203/syllabus#9]
@blulightspecial, could you add office hours to the `./syllabus/schedule/` page (beneath the line that Leslie added), and issue a PR that closes this issue?

**Comment by blulightspecial** [comment]
How do we close this guy?

**Comment by d-alex-hughes** [comment]
Did you add your office hours? If not, then if you make the change, commit and PR, then I'll close the issue. 

If you mention #9 in the PR, then it will link the PR and issue and make my life easier. Do sweat it though.

**Comment by blulightspecial** [comment]
My hours are up and the PR (#10) has already been approved my dude. https://github.com/mids-w203/syllabus/pull/10
